version: '3.4'
services:
  # db_mysql:
  #   hostname: mysql
  #   image: orchardup/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: p@ssw0rd123
  #     MYSQL_DATABASE: hacktober18  
  web:
    build: .
    command: bash -c "python /code/manage.py create_db && python /code/manage.py runserver"
    ports:
    - "9000:9000"
    volumes:
    - .:/code
    hostname: myappserver
    environment:
    - PROJECT_DEVELOPMENT_DATABASE_URI=mysql://root:@ssw0rd123@mysql/hacktober18
